server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 42.193.4.65:8848 #配置Nacos地址
      config:
        file-extension: yml # 文件后缀名

management:
  endpoints:
    web:
      exposure:
        include: '*'  #默认只公开了/health和/info端点，要想暴露所有端点只需设置成星号