# tomcat配置
server:
  tomcat:
    uri-encoding: utf-8
    connection-timeout: 5000ms

  port: 80
  servlet:
    #    context-path: /emos-wx-api
    encoding:
      charset: utf-8
#      enabled: true
#      force: true
# mysql数据源
spring:
  application:
    name: cloud-consumer-feign-order80
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  MaxAutoRetries: 1 #同一台实例最大重试次数,不包括首次调用
  MaxAutoRetriesNextServer: 1 #重试负载均衡其他的实例最大重试次数,不包括首次调用
  OkToRetryOnAllOperations: false

logging:
  level:
    com.zym.springcloud.service.PaymentFeignService: debug